# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, Return, exec, $terminal
bind = $mainMod, m, exec, hyprlock --grace 2
bind = $mainMod, z, exec, wlogout
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, D, exec, $menu
bind = $mainMod, B, exec, helium-browser

bind = , XF86SelectiveScreenshot, exec, grim - | wl-copy && notify-send "Screenshot copiato negli appunti"
bind = SHIFT, XF86SelectiveScreenshot, exec, grim && notify-send "Screenshot salvato"
bind = CTRL, XF86SelectiveScreenshot, exec, grim -g "$(slurp)" - | wl-copy && notify-send "Screenshot copiato negli appunti"
bind = CTRL SHIFT, XF86SelectiveScreenshot, exec, grim -g "$(slurp)" && notify-send "Screenshot salvato"
