##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

windowrule = size 350 450,initialClass:org.kde.kcalc
windowrule = center,initialClass:org.kde.kcalc
windowrule = float,initialClass:org.kde.kcalc

windowrule = size 350 450,initialClass:it.mijorus.smile
windowrule = center,initialClass:it.mijorus.smile
windowrule = float,initialClass:it.mijorus.smile
windowrule = stayfocused,initialClass:it.mijorus.smile

windowrule {
  name = windowrule-jb-tag
  tag = +jb
  match:class = ^jetbrains-.*
  match:initial_title = ""
}

windowrule {
  name = windowrule-jb-focus
  focus_on_activate = on
  no_initial_focus = on
  float=off
  match:tag = jb
}
