$terminal = foot
$fileManager = pcmanfm-qt
$menu = rofi

bind = $mainMod, D, exec, $menu -show drun -show-icons
bind = $mainMod SHIFT, D, exec, $menu -show run

bind = $mainMod, Return, exec, $terminal

bind = $mainMod, Z, exec, wlogout -c 10 -L 300 -R 300 -B 435 -T 435 -b 6
bind = $mainMod, C, exec, ~/.config/wofi/copyq.sh
bind = $mainMod, b, exec, zen-browser
bind = $mainMod, E, exec, $fileManager
bind = $mainMod SHIFT, E, exec, smile
