# Volume
bindel=, XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+
bindel=, XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl=, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# Wake/sleep
bindl=$mainMod SHIFT, l, exec, sleep 1 && hyprctl dispatch dpms off
bind=$mainMod SHIFT, k, dpms, on

# Screenshot
bind=SHIFT, Print, exec, grim -g "$(slurp -d)" - | wl-copy && notify-send "Screenshot copiato negli appunti"
bind=, Print, exec, grim -| wl-copy && notify-send "Screenshot copiato negli appunti"
bind=CTRL, Print, exec, copyq read image/png > ~/Immagini/Schermate/Screenshot-$(date).png && notify-send "Screenshot salvato"

# Wiki
bind = $mainMod SHIFT, code:20, exec, xdg-open https://wiki.hyprland.org/

# Zoom
bind = $mainMod, mouse:275, exec, ~/.config/hypr/zoom.py 0.2 1
bind = $mainMod, mouse:276, exec, ~/.config/hypr/zoom.py 0.2

# Alt tab
bind = ALT, TAB, cyclenext,
bind = ALT SHIFT, TAB, cyclenext, prev

bind = $mainMod, w, exec, hyprctl hyprpaper wallpaper 'DP-3,/home/amedeo/Immagini/sfondo-2.webp'
bind = $mainMod SHIFT, w, exec, hyprctl hyprpaper wallpaper 'DP-3,/home/amedeo/Immagini/sfondo.png'
