windowrule = match:initial_title ^(Godot)$, float on
windowrule = match:initial_title ^(Smile)$, float on
windowrule = match:initial_title ^(pavucontrol-qt)$, float on
windowrule = match:initial_title (org.kde.kcalc), float on
windowrule = match:initial_title (^Minecraft.*$), immediate on
windowrule = match:initial_class ^(packettracer6.exe)$, suppress_event fullscreen maximize activate activatefocus
